[package]
name = "lattice-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tempfile = "3"
lattice-core = { path = "../crates/lattice-core" }
lattice-collectors = { path = "../crates/lattice-collectors", features = ["fuzzing"] }
lattice-tracer = { path = "../crates/lattice-tracer" }

[workspace]

[profile.release]
debug = 1

[[bin]]
name = "pki"
path = "fuzz_targets/pki.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keys"
path = "fuzz_targets/keys.rs"
test = false
doc = false
bench = false

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false
bench = false

[[bin]]
name = "source"
path = "fuzz_targets/source.rs"
test = false
doc = false
bench = false

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
test = false
doc = false
bench = false

[[bin]]
name = "capture"
path = "fuzz_targets/capture.rs"
test = false
doc = false
bench = false

[[bin]]
name = "container"
path = "fuzz_targets/container.rs"
test = false
doc = false
bench = false

[[bin]]
name = "names"
path = "fuzz_targets/names.rs"
test = false
doc = false
bench = false

[[bin]]
name = "gopclntab"
path = "fuzz_targets/gopclntab.rs"
test = false
doc = false
bench = false
