server {
    listen 443 ssl;
    server_name pay.example.gov.in;

    ssl_certificate     /etc/nginx/tls/server.crt;
    ssl_certificate_key /etc/nginx/tls/legacy.key;
    ssl_protocols       TLSv1 TLSv1.2;
    ssl_ciphers         ECDHE-RSA-AES128-GCM-SHA256:DES-CBC3-SHA;

    location /v1/payments { proxy_pass http://payments-api:8000; }
    location /v1/citizen  { proxy_pass http://identity-service:8080; }
}
